---
  # Result files
  RESULTS_DIR: "results"

  # Data files
  DATA_DIR: "data"
  STATS_DIR: "data/stats"
  KV_DIR: "data/cache/kvs"

  # Hyperparameters
  HPARAMS_DIR: "src/memit_project/algorithms"

  # Remote URLs
  REMOTE_ROOT_URL: "https://memit.baulab.info"
